steps:
# 1. Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/my-app:$COMMIT_SHA' # Ruta en Artifact Registry
  - '.'

# 2. Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/my-app:$COMMIT_SHA'

# 3. Desplegar la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  args:
  - 'gcloud'
  - 'run'
  - 'deploy'
  - 'my-app-service' # Nombre que tendrá tu servicio en Cloud Run
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/my-app:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'